spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasktracker
    username: postgres
    password: 00889977





  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 8888
